import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import Navbar from "@/components/navbar";
import ActiveSectionContextProvider from "@/context/active-section-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark !scroll-smooth">
      <body className={inter.className}>
        <main className="relative overflow-hidden bg-slate-950">
          <ActiveSectionContextProvider>
          <Navbar/>
          <Header/>
          {children}
          </ActiveSectionContextProvider>
        </main>
        </body>
    </html>
  );
}
